# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/learning-nbdev',
                'doc_host': 'https://smithjessk.github.io',
                'git_url': 'https://github.com/smithjessk/learning-nbdev',
                'lib_path': 'learning_nbdev'},
  'syms': {'learning_nbdev.core': {'learning_nbdev.core.foo': ('core.html#foo', 'learning_nbdev/core.py')}}}