# AUTOGENERATED! DO NOT EDIT! File to edit: ../gonna_be_rich.ipynb.

# %% auto 0
__all__ = ['add', 'sub']

# %% ../gonna_be_rich.ipynb 3
def add(x, y):
    '''Add two numbers together '''
    return x + y

# %% ../gonna_be_rich.ipynb 5
def sub(x, y):
    '''Subtract two numbers'''
    return x - y
